obj-y := dev.o dev_disk.o dev_null.o dev_stdin.o dev_stdout.o dev_urandom.o dev_uio.o dev_zynq_programmable_logic.o

obj-$(UCONFIG_DDE_MMC_UCORE_BLOCK) += dev_mmc0.o
obj-$(UCONFIG_MIPS_ENABLE_THINPAD_FLASH_DRIVER) += dev_thinpad_flashrom.o
